# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../financemanager/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 791, 551))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.config = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.config.setObjectName("config")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.config)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 771, 141))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.setObjectName("layout")
        self.companies = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.companies.setObjectName("companies")
        self.label = QtWidgets.QLabel(self.companies)
        self.label.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label.setObjectName("label")
        self.layout.addWidget(self.companies)
        self.dates = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.dates.setObjectName("dates")
        self.label_2 = QtWidgets.QLabel(self.dates)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_2.setObjectName("label_2")
        self.begin = QtWidgets.QDateEdit(self.dates)
        self.begin.setGeometry(QtCore.QRect(30, 80, 110, 22))
        self.begin.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.begin.setObjectName("begin")
        self.end = QtWidgets.QDateEdit(self.dates)
        self.end.setGeometry(QtCore.QRect(230, 80, 110, 22))
        self.end.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.end.setObjectName("end")
        self.label_3 = QtWidgets.QLabel(self.dates)
        self.label_3.setGeometry(QtCore.QRect(50, 50, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.dates)
        self.label_4.setGeometry(QtCore.QRect(250, 50, 47, 13))
        self.label_4.setObjectName("label_4")
        self.layout.addWidget(self.dates)
        self.calculate = QtWidgets.QPushButton(self.config)
        self.calculate.setGeometry(QtCore.QRect(710, 150, 75, 23))
        self.calculate.setObjectName("calculate")
        self.verticalLayout.addWidget(self.config)
        self.stats = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.stats.setObjectName("stats")
        self.statsList = QtWidgets.QListWidget(self.stats)
        self.statsList.setGeometry(QtCore.QRect(15, 1, 761, 171))
        self.statsList.setObjectName("statsList")
        self.verticalLayout.addWidget(self.stats)
        self.notfound = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.notfound.setObjectName("notfound")
        self.notfoundlist = QtWidgets.QListWidget(self.notfound)
        self.notfoundlist.setGeometry(QtCore.QRect(10, 10, 771, 161))
        self.notfoundlist.setObjectName("notfoundlist")
        self.verticalLayout.addWidget(self.notfound)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Companies"))
        self.label_2.setText(_translate("MainWindow", "Date filter"))
        self.begin.setDisplayFormat(_translate("MainWindow", "yyyy. MM."))
        self.end.setDisplayFormat(_translate("MainWindow", "yyyy. MM."))
        self.label_3.setText(_translate("MainWindow", "from"))
        self.label_4.setText(_translate("MainWindow", "to"))
        self.calculate.setText(_translate("MainWindow", "Calculate"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
